ALTER PROC dbo.sproc_check_plantimeinterval
(
@AgentId  varchar(10)
)
As
BEGIN

DECLARE @starttime TIME(0),
        @endtime TIME(0),
        @interval INT = 30,
		@SecondLastTime Varchar(5),
		@Count INT

SELECT @StartTime = ClubOpeningTime,
       @EndTime = ClubClosingTime
FROM tbl_club_details
WHERE AgentId = @AgentId;

-- Create a temporary table to store the result of the CTE
CREATE TABLE #Temp (  
    TimeInterval TIME
);

-- Insert the time intervals generated by the CTE into the temporary table
WITH cte AS (    
         SELECT  
		    CAST(CONVERT(CHAR(8), @starttime, 108) AS TIME) AS TimeInterval
    UNION ALL
    SELECT 
           CAST(DATEADD(MINUTE, @interval, TimeInterval) AS TIME)
    FROM cte
    WHERE CAST(DATEADD(MINUTE, @interval, TimeInterval) AS TIME) < @endtime
)
INSERT INTO #Temp (TimeInterval)
  SELECT  TimeInterval
  FROM cte;


   WITH NumberedRows AS (
       SELECT ROW_NUMBER() OVER (ORDER BY TimeInterval) AS RowNum,
             LEFT(CONVERT(VARCHAR, TimeInterval, 108), 5) AS TimeInterval  
       FROM #Temp
   )

   

----------------------------------START update plan according to time interval if doesnot exist -----------------------------------------
  SELECT 
       @SecondLastTime= TimeInterval
   FROM 
       NumberedRows
   WHERE 
       RowNum = (SELECT MAX(RowNum) - 1 FROM NumberedRows);

   SELECT 
        @Count=Count (*)
   FROM 
        tbl_club_plan
   WHERE 
        clubid = @AgentId
   AND 
        ClubPlanTypeId IN (2, 3)   
   AND 
       Description NOT IN
   	(
           SELECT TimeInterval
           FROM #Temp
     );


   IF	@Count>0
   BEGIN
     update tbl_club_plan SET Description= @SecondLastTime 
     	WHERE 
     	    ClubId=@AgentId
     		AND ClubPlanTypeId IN (2, 3)  
     		And Id in 
                  (SELECT 
     	               Id
                   FROM 
     	               tbl_club_plan
                   WHERE 
     	              clubid = @AgentId
                   AND ClubPlanTypeId IN (2, 3)   
                   AND Description
     	          NOT IN
     	               (
                            SELECT TimeInterval
                            FROM #Temp
                        )
     	          )
   	END
DROP TABLE #Temp;

----------------------------------END update plan according to time interval -----------------------------------------

----------------------------------Start to update lastorder time and last entry time ---------------------------------------------------
declare @ClubClosingTime varchar(5),@LastEntrySyokai varchar(5)
select  @ClubClosingTime=CONVERT(TIME, DATEADD(MINUTE, -60, ClubClosingTime))  from tbl_club_details where agentId =@AgentId 


IF NOT EXISTS(select 'x' from tbl_club_details where agentId =@AgentId and 
lastordertime between ClubOpeningTime and ClubClosingTime 
)
BEGIN
   UPDATE tbl_club_details set lastordertime=isnull(@ClubClosingTime,lastordertime)  where agentId =@AgentId
END

IF NOT EXISTS(select  'x' from tbl_club_details where agentId =@AgentId and 
LastEntrySyokai between ClubOpeningTime and ClubClosingTime
)
BEGIN
   UPDATE tbl_club_details set LastEntrySyokai=isnull(@ClubClosingTime,LastEntrySyokai)  where agentId =@AgentId
END


----------------------------------END to update lastorder time and last entry time ---------------------------------------------------
END