USE CRS
GO

CREATE TABLE tbl_menus_role
(
	Sno BIGINT IDENTITY(1,2) PRIMARY KEY,
	RoleId BIGINT NULL,
	MenuId BIGINT NULL,
	ActionUser VARCHAR(200) NULL,
	ActionIP VARCHAR(50) NULL,
	ActionDate DATETIME NULL
)