USE [CRS]
GO

/****** Object:  Table [dbo].[tbl_affiliate_hold]    Script Date: 12/12/2023 11:37:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_affiliate_hold](
	[Sno] [BIGINT] IDENTITY(1,2) NOT NULL,
	[HoldAgentId] [BIGINT] NULL,
	[FirstName] [NVARCHAR](200) NULL,
	[LastName] [NVARCHAR](200) NULL,
	[MobileNumber] [VARCHAR](15) NULL,
	[EmailAddress] [VARCHAR](512) NULL,
	[DOB] [VARCHAR](20) NULL,
	[Gender] [VARCHAR](10) NULL,
	[SnsType] [VARCHAR](10) NULL,
	[SnsURLLink] [VARCHAR](MAX) NULL,
	[Status] [CHAR](1) NULL,
	[CreatedBy] [VARCHAR](200) NULL,
	[CreatedIP] [VARCHAR](50) NULL,
	[CreatedPlatform] [VARCHAR](20) NULL,
	[CreatedDate] [DATETIME] NULL,
	[UpdatedBy] [VARCHAR](200) NULL,
	[UpdatedIP] [VARCHAR](50) NULL,
	[UpdatedPlatform] [VARCHAR](20) NULL,
	[UpdatedDate] [DATETIME] NULL,
PRIMARY KEY CLUSTERED 
(
	[Sno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

