USE [CRS]
GO

/****** Object:  Table [dbo].[tbl_holiday]    Script Date: 2/21/2024 9:22:21 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_holiday](
	[Id] [INT] IDENTITY(1,1) NOT NULL,
	[EnglishDay] [VARCHAR](200) NULL,
	[JapaneseDay] [NVARCHAR](200) NULL,
 CONSTRAINT [PK_tbl_holiday] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


