USE [CRS]
GO

/****** Object:  Table [dbo].[tbl_review_and_rating]    Script Date: 27/11/2023 14:56:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[tbl_review_and_rating](
	[Sno] [BIGINT] IDENTITY(1,2) NOT NULL,
	[ReviewId] [BIGINT] NULL,
	[ReservationId] [BIGINT] NULL,
	[CustomerId] [BIGINT] NULL,
	[ClubId] [BIGINT] NULL,
	[HostList] [VARCHAR](MAX) NULL,
	[MVPHostId] [VARCHAR](10) NULL,
	[RemarkList] [VARCHAR](MAX) NULL,
	[RatingScale] [INT] NULL,
	[Status] CHAR(1) NULL,
	[ActionUser] [VARCHAR](200) NULL,
	[ActionDate] [DATETIME] NULL,
	[ActionIP] [VARCHAR](20) NULL,
	[ActionPlatform] [VARCHAR](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[Sno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

